# Generated by Django 5.1.4 on 2024-12-05 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Marka Adı')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('resim', models.ImageField(upload_to='slider_resimleri/', verbose_name='Slider Resmi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='toner_resimleri/', verbose_name='Resim')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonerler', to='website.marka', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Toner',
                'verbose_name_plural': 'Tonerler',
                'ordering': ['marka', 'model'],
            },
        ),
        migrations.CreateModel(
            name='TonerResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='toner_resimleri/', verbose_name='Toner Resmi')),
                ('toner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='website.toner', verbose_name='Toner')),
            ],
            options={
                'verbose_name': 'Toner Resmi',
                'verbose_name_plural': 'Toner Resimleri',
            },
        ),
    ]
